[package]
name = "menu-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.31.0"
chrono = "0.4.42"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
simplelog = "0.12.2"
tera = "1.20.0"
which = "8.0.0"
